### ISSUE TITLE
Is this repo being maintained?

### ISSUE THREAD

**Issue by febincloudyuga** [tallytarik/ruby-iplocate#1]
Seems to break with Rails 6.  Is this repo going to be maintained?

**Comment by tallytarik** [comment]
Can you provide some more details? The gem isn’t related to Rails so you should be able to use it with any version.

**Comment by febincloudyuga** [comment]
The current version of this gem (1.0.1) has a dependency on activesupport ~> 5.1, whereas Rails expects 6.0.2.2

![Screen Shot 2020-04-23 at 12 55 39 PM](https://user-images.githubusercontent.com/29917673/80090747-9c6cbe80-857d-11ea-898a-5cd0c69a1d0a.png)

**Comment by tallytarik** [comment]
Aha, good catch! Happy to accept a PR for this one, otherwise I’ll get to this later in the week.

**Comment by tallytarik** [comment]
Fixed in 1.0.2.
